### ISSUE TITLE
Opportunity to support JSON Format?

### ISSUE THREAD

**Issue by elebescond** [42Zavattas/Restock.io#1]
http://json-schema.org/

Feature inspiration: http://jsonschema.net/reboot/

**Comment by balthazar** [comment]
Unfortunately, I don't think this kind of thing will match the true purpose of _Restock_ :tm:, a fast way to get mock data using a simple query.

I can see the interest of it, but this should be a totally separate project that can potentially take results from _Restock_ :tm: and then convert it.

Anyway, we'll wait for the input of @meriadec before closing this.

**Comment by meriadec** [comment]
Well.
I agree with your point of view. _Restock_ ( ® , © , ™ , ![Label Pur](http://www.soun-music.com/px/actualite/154/image/154_50_50_CROPMAX_cea8f.jpg) ) is something and not something else. As you said, it has been built for two particular _purposes_ :
1. build a better world
2. giving people _for **free**_ — we need to talk — the opportunity of _mocking their http calls in a blink of an eye_

I think the attractiveness of _Restock_ (4 stars when I write thoses lines !!) is to be ultra fast to use.
It is that who makes it so popular accross the developper community.
It is Restock.

_Restocking regards._
